#!/bin/sh

# Script to run the Qt client from the build directory

if [ -x yate-qt -a -x ../run ]; then
    cd ..; exec ./run --executable clients/yate-qt "$@"
else
    echo "Could not find client executable or run script" >&2
fi
