#!/bin/sh

# Run this to generate a new configure script

if [ -x yate-qt -a -x ../run ]; then
    cd ..; exec ./run --executable clients/yate-qt "$@"
else
    echo "Could not find client executable or run script" >&2
fi
