# Makefile
# This file holds the make rules for the Telephony Engine

all: all.h

all.h: ./gen.c ./gen.sh ./gen.awk
	./gen.sh "."

.PHONY: clean
clean:
	rm -f *.raw ?2? gen core*

.PHONY: mrproper
mrproper: clean
	rm -f *.h

.PHONY: strip
strip: all

install:

uninstall:
