debian/tmp/usr/lib/libyate.so.*

debian/tmp/etc/yate/callfork.conf
debian/tmp/etc/yate/cdrbuild.conf
debian/tmp/etc/yate/cdrfile.conf
#debian/tmp/etc/yate/dsoundchan.conf
debian/tmp/etc/yate/enumroute.conf
debian/tmp/etc/yate/extmodule.conf
debian/tmp/etc/yate/moh.conf
debian/tmp/etc/yate/mux.conf
debian/tmp/etc/yate/providers.conf
debian/tmp/etc/yate/regexroute.conf
debian/tmp/etc/yate/rmanager.conf
debian/tmp/etc/yate/yate.conf
debian/tmp/etc/yate/yiaxchan.conf
debian/tmp/etc/yate/yjinglechan.conf
debian/tmp/etc/yate/yrtpchan.conf
debian/tmp/etc/yate/ysipchan.conf
debian/tmp/etc/yate/ystunchan.conf
debian/tmp/etc/yate/openssl.conf
debian/tmp/etc/yate/tonegen.conf

debian/tmp/usr/lib/yate/*codec.yate
debian/tmp/usr/lib/yate/client/osschan.yate usr/lib/yate
debian/tmp/usr/lib/yate/cdrbuild.yate
debian/tmp/usr/lib/yate/cdrfile.yate
debian/tmp/usr/lib/yate/regexroute.yate
debian/tmp/usr/lib/yate/tonegen.yate
debian/tmp/usr/lib/yate/tonedetect.yate
debian/tmp/usr/lib/yate/wavefile.yate
debian/tmp/usr/lib/yate/extmodule.yate
debian/tmp/usr/lib/yate/conference.yate
debian/tmp/usr/lib/yate/moh.yate
debian/tmp/usr/lib/yate/pbx.yate
debian/tmp/usr/lib/yate/dumbchan.yate
debian/tmp/usr/lib/yate/callfork.yate
debian/tmp/usr/lib/yate/mux.yate
debian/tmp/usr/lib/yate/yrtpchan.yate
debian/tmp/usr/lib/yate/ystunchan.yate
debian/tmp/usr/lib/yate/ysipchan.yate
debian/tmp/usr/lib/yate/yiaxchan.yate
debian/tmp/usr/lib/yate/callgen.yate
debian/tmp/usr/lib/yate/analyzer.yate
debian/tmp/usr/lib/yate/rmanager.yate
debian/tmp/usr/lib/yate/msgsniff.yate
debian/tmp/usr/lib/yate/enumroute.yate
debian/tmp/usr/lib/yate/openssl.yate

debian/tmp/etc/yate/ysockschan.conf
debian/tmp/usr/lib/yate/ysockschan.yate

debian/tmp/etc/yate/filetransfer.conf
debian/tmp/usr/lib/yate/filetransfer.yate

debian/tmp/usr/share/yate/sounds/ring.wav
debian/tmp/usr/share/yate/sounds/tone.wav

debian/tmp/usr/lib/libyatejabber.so.*
debian/tmp/usr/lib/yate/yjinglechan.yate

debian/tmp/etc/yate/zlibcompress.conf
debian/tmp/usr/lib/yate/zlibcompress.yate

debian/tmp/etc/yate/jabberclient.conf
debian/tmp/usr/lib/yate/client/jabberclient.yate usr/lib/yate


