## analog and isdn cards ##
debian/tmp/usr/lib/libyatesig.so.*
debian/tmp/usr/lib/libyatesig.so
debian/tmp/etc/yate/analog.conf
debian/tmp/usr/lib/yate/server/analog.yate
#debian/tmp/etc/yate/wpcard.conf
#debian/tmp/usr/lib/yate/server/wpcard.yate
debian/tmp/etc/yate/zapcard.conf
debian/tmp/usr/lib/yate/server/zapcard.yate
debian/tmp/etc/yate/ysigchan.conf
debian/tmp/usr/lib/yate/server/ysigchan.yate
debian/tmp/etc/yate/ciscosm.conf
debian/tmp/usr/lib/yate/server/ciscosm.yate
debian/tmp/etc/yate/mgcpca.conf
debian/tmp/usr/lib/yate/server/mgcpca.yate
debian/tmp/etc/yate/sigtransport.conf
debian/tmp/usr/lib/yate/server/sigtransport.yate
debian/tmp/etc/yate/isupmangler.conf
debian/tmp/usr/lib/yate/sig/isupmangler.yate
debian/tmp/etc/yate/ss7_lnp_ansi.conf
debian/tmp/usr/lib/yate/sig/ss7_lnp_ansi.yate

