debian/tmp/usr/bin/yate
debian/tmp/usr/share/man/man8/yate.8

## scripts ##
debian/tmp/usr/share/yate/scripts/libyate.php
debian/tmp/usr/share/yate/scripts/libyateivr.php
debian/tmp/usr/share/yate/scripts/libyatechan.php
debian/tmp/usr/share/yate/scripts/libvoicemail.php
debian/tmp/usr/share/yate/scripts/libyate.py
debian/tmp/usr/share/yate/scripts/Yate.pm
debian/tmp/usr/share/yate/scripts/leavemail.php
debian/tmp/usr/share/yate/scripts/voicemail.php
debian/tmp/usr/share/yate/scripts/route.php
debian/tmp/usr/share/yate/scripts/queue_in.php
debian/tmp/usr/share/yate/scripts/queue_out.php

## server-only conf files ##
debian/tmp/etc/yate/pbxassist.conf
debian/tmp/usr/lib/yate/server/pbxassist.yate
debian/tmp/etc/yate/dbpbx.conf
debian/tmp/usr/lib/yate/server/dbpbx.yate
debian/tmp/etc/yate/lateroute.conf
debian/tmp/usr/lib/yate/server/lateroute.yate
debian/tmp/usr/lib/yate/server/park.yate
debian/tmp/etc/yate/queues.conf
debian/tmp/usr/lib/yate/server/queues.yate
debian/tmp/etc/yate/regfile.conf
debian/tmp/usr/lib/yate/server/regfile.yate
debian/tmp/etc/yate/accfile.conf
debian/tmp/usr/lib/yate/server/accfile.yate
debian/tmp/etc/yate/register.conf
debian/tmp/usr/lib/yate/server/register.yate
debian/tmp/etc/yate/yradius.conf
debian/tmp/usr/lib/yate/server/yradius.yate
debian/tmp/etc/yate/sipfeatures.conf
debian/tmp/usr/lib/yate/server/sipfeatures.yate
debian/tmp/etc/yate/heartbeat.conf
debian/tmp/usr/lib/yate/server/heartbeat.yate
debian/tmp/etc/yate/clustering.conf
debian/tmp/usr/lib/yate/server/clustering.yate
debian/tmp/usr/lib/libyatemgcp.so*
debian/tmp/etc/yate/mgcpgw.conf
debian/tmp/usr/lib/yate/server/mgcpgw.yate
debian/tmp/usr/lib/yate/server/mrcpspeech.yate
debian/tmp/usr/lib/yate/server/analogdetect.yate
debian/tmp/usr/lib/yate/server/dbwave.yate

debian/tmp/etc/yate/queuesnotify.conf
debian/tmp/usr/lib/yate/server/queuesnotify.yate

debian/tmp/etc/yate/callcounters.conf
debian/tmp/usr/lib/yate/server/callcounters.yate

debian/tmp/etc/yate/presence.conf
debian/tmp/usr/lib/yate/server/presence.yate

debian/tmp/etc/yate/subscription.conf
debian/tmp/usr/lib/yate/server/subscription.yate

debian/tmp/etc/yate/users.conf
debian/tmp/usr/lib/yate/server/users.yate

debian/tmp/etc/yate/jabberserver.conf
debian/tmp/usr/lib/yate/jabber/jabberserver.yate
debian/tmp/etc/yate/jbfeatures.conf
debian/tmp/usr/lib/yate/jabber/jbfeatures.yate

debian/tmp/etc/yate/ysnmpagent.conf
debian/tmp/usr/lib/yate/server/ysnmpagent.yate
debian/tmp/usr/share/yate/data/snmp_mib.conf
debian/tmp/usr/share/yate/data/NULL-TEAM-MIB.txt
debian/tmp/usr/share/yate/data/YATE-MIB.txt

debian/tmp/etc/yate/monitoring.conf
debian/tmp/usr/lib/yate/server/monitoring.yate

debian/tmp/etc/yate/cpuload.conf
debian/tmp/usr/lib/yate/server/cpuload.yate
debian/tmp/etc/yate/ccongestion.conf
debian/tmp/usr/lib/yate/server/ccongestion.yate

debian/tmp/usr/lib/yate/server/overlapdial.yate

debian/tmp/etc/yate/sip_cnam_lnp.conf
debian/tmp/usr/lib/yate/sip/sip_cnam_lnp.yate

debian/tmp/etc/yate/cache.conf
debian/tmp/usr/lib/yate/server/cache.yate

