debian/tmp/usr/bin/yate
debian/tmp/usr/share/man/man8/yate.8

## scripts ##
debian/tmp/usr/share/yate/scripts/libyate.php
debian/tmp/usr/share/yate/scripts/libyateivr.php
debian/tmp/usr/share/yate/scripts/libyatechan.php
debian/tmp/usr/share/yate/scripts/libvoicemail.php
debian/tmp/usr/share/yate/scripts/libyate.py
debian/tmp/usr/share/yate/scripts/Yate.pm
debian/tmp/usr/share/yate/scripts/leavemail.php
debian/tmp/usr/share/yate/scripts/voicemail.php
debian/tmp/usr/share/yate/scripts/route.php
debian/tmp/usr/share/yate/scripts/queue_in.php
debian/tmp/usr/share/yate/scripts/queue_out.php

## server-only conf files ##
debian/tmp/etc/yate/pbxassist.conf
debian/tmp/usr/lib/yate/server/pbxassist.yate
debian/tmp/etc/yate/dbpbx.conf
debian/tmp/usr/lib/yate/server/dbpbx.yate
debian/tmp/etc/yate/lateroute.conf
debian/tmp/usr/lib/yate/server/lateroute.yate
debian/tmp/usr/lib/yate/server/park.yate
debian/tmp/etc/yate/queues.conf
debian/tmp/usr/lib/yate/server/queues.yate
debian/tmp/etc/yate/regfile.conf
debian/tmp/usr/lib/yate/server/regfile.yate
debian/tmp/etc/yate/accfile.conf
debian/tmp/usr/lib/yate/server/accfile.yate
debian/tmp/etc/yate/register.conf
debian/tmp/usr/lib/yate/server/register.yate
debian/tmp/etc/yate/yradius.conf
debian/tmp/usr/lib/yate/server/yradius.yate
debian/tmp/etc/yate/sipfeatures.conf
debian/tmp/usr/lib/yate/server/sipfeatures.yate
debian/tmp/etc/yate/heartbeat.conf
debian/tmp/usr/lib/yate/server/heartbeat.yate
debian/tmp/etc/yate/clustering.conf
debian/tmp/usr/lib/yate/server/clustering.yate
debian/tmp/usr/lib/libyatemgcp.so*
debian/tmp/etc/yate/mgcpgw.conf
debian/tmp/usr/lib/yate/server/mgcpgw.yate
debian/tmp/usr/lib/yate/server/mrcpspeech.yate
debian/tmp/usr/lib/yate/server/analogdetect.yate
debian/tmp/usr/lib/yate/server/overlapdial.yate
debian/tmp/usr/lib/yate/server/dbwave.yate

debian/tmp/etc/yate/queuesnotify.conf
debian/tmp/usr/lib/yate/server/queuesnotify.yate

debian/tmp/etc/yate/callcounters.conf
debian/tmp/usr/lib/yate/server/callcounters.yate

debian/tmp/usr/lib/yate/server/presence.yate
debian/tmp/usr/lib/yate/server/subscription.yate
debian/tmp/usr/lib/yate/server/users.yate

debian/tmp/etc/yate/jabberserver.conf
debian/tmp/usr/lib/yate/jabber/jabberserver.yate
debian/tmp/etc/yate/jbfeatures.conf
debian/tmp/usr/lib/yate/jabber/jbfeatures.yate

