#!/bin/sh

# Script to run the SS7 test from the build directory

exefile="yate-ss7test"
if [ -x "$exefile" -a -x ../../run ]; then
    cd ../..; exec ./run --executable "libs/ysig/$exefile" "$@"
else
    echo "Could not find '$exefile' executable or run script" >&2
fi
