#!/bin/sh

# run-ss7test
# This file is part of the YATE Project http://YATE.null.ro
#
# Yet Another Telephony Engine - a fully featured software PBX and IVR
# Copyright (C) 2005-2014 Null Team
#
# This software is distributed under multiple licenses;
# see the COPYING file in the main directory for licensing
# information for this specific distribution.
#
# This use of this software may be subject to additional restrictions.
# See the LEGAL file in the main directory for details.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


# Script to run the SS7 test from the build directory

exefile="yate-ss7test"
if [ -x "$exefile" -a -x ../../run ]; then
    cd ../..; exec ./run --executable "libs/ysig/$exefile" "$@"
else
    echo "Could not find '$exefile' executable or run script" >&2
fi
